/**
 * Content generation for Peria wiki pages
 */

import type { PeriaManifest } from '@peria/core';
import { encodePackageName, encodeRoutePath } from './config.js';
import type {
  DocsMetadata,
  DriftFindingData,
  GeneratedPage,
  HttpMethod,
  PackagePageData,
  RoutePageData,
  SchemaPageData,
  Severity,
} from './types.js';

export interface ContentGenerationOptions {
  /**
   * The Peria manifest to generate content from
   */
  manifest: PeriaManifest;

  /**
   * Base URL for links
   * @default '/docs'
   */
  baseUrl?: string;

  /**
   * Include routes in generated pages
   * @default true
   */
  includeRoutes?: boolean;

  /**
   * Include packages in generated pages
   * @default true
   */
  includePackages?: boolean;

  /**
   * Include schemas in generated pages
   * @default true
   */
  includeSchemas?: boolean;

  /**
   * Include drift report
   * @default true
   */
  includeDrift?: boolean;
}

/**
 * Generate documentation pages from Peria manifest
 */
export function generatePagesFromManifest(options: ContentGenerationOptions): {
  metadata: DocsMetadata;
  routes: RoutePageData[];
  packages: PackagePageData[];
  schemas: SchemaPageData[];
  driftFindings: DriftFindingData[];
  pages: GeneratedPage[];
} {
  const {
    manifest,
    baseUrl = '/docs',
    includeRoutes = true,
    includePackages = true,
    includeSchemas = true,
    includeDrift = true,
  } = options;

  // Generate metadata
  const metadata: DocsMetadata = {
    title: 'Peria Documentation',
    description: 'API documentation generated by Peria',
    generatedAt: manifest.generatedAt,
    manifestVersion: manifest.manifestVersion,
    periaVersion: manifest.periaVersion,
    git: manifest.git
      ? {
          branch: manifest.git.branch,
          commit: manifest.git.shortCommit,
          isDirty: manifest.git.isDirty,
        }
      : undefined,
    stats: {
      routes: manifest.routes?.length ?? 0,
      packages: manifest.packages?.length ?? 0,
      schemas: manifest.schemas?.length ?? 0,
      pages: manifest.docsPages?.length ?? 0,
      driftFindings: manifest.drift?.length ?? 0,
      modules: 0,
    },
  };

  // Generate route pages
  const routes: RoutePageData[] = includeRoutes ? generateRoutePages(manifest.routes ?? []) : [];

  // Generate package pages
  const packages: PackagePageData[] = includePackages
    ? generatePackagePages(manifest.packages ?? [])
    : [];

  // Generate schema pages
  const schemas: SchemaPageData[] = includeSchemas
    ? generateSchemaPages(manifest.schemas ?? [])
    : [];

  // Generate drift findings
  const driftFindings: DriftFindingData[] = includeDrift
    ? generateDriftFindings(manifest.drift ?? [])
    : [];

  // Generate additional pages
  const pages: GeneratedPage[] = [
    // Overview
    {
      slug: 'overview',
      title: 'Documentation Overview',
      description: 'Overview of the generated documentation',
      content: generateOverviewPage(manifest, metadata, baseUrl),
      url: `${baseUrl}/overview`,
      category: 'start',
      order: 1,
    },
    // Route pages
    ...routes.map((route) => ({
      slug: `routes/${encodeRoutePath(route.path)}`,
      title: `${route.method} ${route.path}`,
      description: route.summary ?? route.description,
      content: generateRoutePage(route, baseUrl),
      url: `${baseUrl}/routes/${encodeRoutePath(route.path)}`,
      category: 'api',
      order: 10,
    })),
    // Package pages
    ...packages.map((pkg) => ({
      slug: `packages/${encodePackageName(pkg.name)}`,
      title: pkg.name,
      description: pkg.description,
      content: generatePackagePage(pkg, baseUrl),
      url: `${baseUrl}/packages/${encodePackageName(pkg.name)}`,
      category: 'packages',
      order: 20,
    })),
    // Schema pages
    ...schemas.map((schema) => ({
      slug: `schemas/${schema.name}`,
      title: schema.name,
      description: `Schema with ${schema.properties.length} properties`,
      content: generateSchemaPage(schema, baseUrl),
      url: `${baseUrl}/schemas/${schema.name}`,
      category: 'schemas',
      order: 30,
    })),
    // Drift report
    ...(includeDrift && driftFindings.length > 0
      ? [
          {
            slug: 'drift',
            title: 'Drift Report',
            description: `${driftFindings.length} documentation drift findings`,
            content: generateDriftReportPage(driftFindings),
            url: `${baseUrl}/drift`,
            category: 'maintenance',
            order: 90,
          },
        ]
      : []),
  ];

  return {
    metadata,
    routes,
    packages,
    schemas,
    driftFindings,
    pages,
  };
}

function generateRoutePages(routes: PeriaManifest['routes']): RoutePageData[] {
  return routes.map((route) => ({
    method: route.method as HttpMethod,
    path: route.path,
    handler: route.handler
      ? {
          name: route.handler.name,
          file: route.handler.file,
          line: route.handler.line,
        }
      : undefined,
    schemas:
      route.schemas.length > 0
        ? {
            request: route.schemas[0]
              ? {
                  name: route.schemas[0].name,
                  file: route.schemas[0].file ?? '',
                  line: route.schemas[0].line ?? 0,
                }
              : undefined,
          }
        : undefined,
    openapi: route.openapiOp
      ? {
          operationId: route.openapiOp.operationId,
        }
      : undefined,
    confidence: route.confidence ?? 'medium',
  }));
}

function generatePackagePages(packages: PeriaManifest['packages']): PackagePageData[] {
  return packages.map((pkg) => ({
    name: pkg.name,
    version: pkg.version,
    directory: pkg.source?.file ?? pkg.name,
    description: pkg.description,
    exports:
      pkg.exports?.map((name) => ({
        name,
        type: 'function' as const,
        file: pkg.source?.file ?? '',
        line: 0,
      })) ?? [],
    dependencies: pkg.dependencies ?? [],
    scripts: [],
  }));
}

function generateSchemaPages(schemas: PeriaManifest['schemas']): SchemaPageData[] {
  return schemas.map((schema) => ({
    name: schema.name,
    file: schema.file ?? '',
    line: schema.line ?? 0,
    properties:
      schema.properties?.map((prop) => ({
        name: prop.name,
        type: prop.type ?? 'unknown',
        required: schema.required?.includes(prop.name) ?? false,
        description: prop.description,
      })) ?? [],
    usedBy: [],
    confidence: schema.confidence ?? 'medium',
  }));
}

function generateDriftFindings(drift: PeriaManifest['drift']): DriftFindingData[] {
  return drift.map((d) => ({
    id: d.id,
    severity: d.severity as Severity,
    entityType: d.entityType as DriftFindingData['entityType'],
    entityId: d.entityId ?? d.id,
    entityName: d.entityId ?? d.id,
    problem: d.problem,
    expected: d.expected,
    actual: d.actual,
    evidence: [
      {
        file: d.source.file,
        line: d.source.line,
      },
    ],
    suggestedAction: d.suggestions.join('. ') || 'Review and fix the drift',
    detectedAt: d.source.commit ?? new Date().toISOString(),
  }));
}

function generateOverviewPage(
  manifest: PeriaManifest,
  metadata: DocsMetadata,
  baseUrl: string
): string {
  return `# Documentation Overview

Generated by Peria v${manifest.periaVersion}

## Project Stats

| Metric | Value |
|--------|-------|
| Manifest Version | ${metadata.manifestVersion} |
| Generated | ${new Date(metadata.generatedAt).toLocaleString()} |
${
  metadata.git
    ? `| Branch | ${metadata.git.branch ?? 'unknown'} |
| Commit | \`${metadata.git.commit ?? 'unknown'}\` |
| Status | ${metadata.git.isDirty ? 'Modified' : 'Clean'} |`
    : ''
}

## Coverage

| Category | Count |
|----------|-------|
| Routes | ${metadata.stats?.routes ?? 0} |
| Schemas | ${metadata.stats?.schemas ?? 0} |
| Packages | ${metadata.stats?.packages ?? 0} |
| Documentation | ${metadata.stats?.pages ?? 0} |
| Drift Findings | ${metadata.stats?.driftFindings ?? 0} |

## Quick Links

${metadata.stats?.routes ? `- [API Routes](${baseUrl}/overview#routes)` : ''}
${metadata.stats?.packages ? `- [Packages](${baseUrl}/overview#packages)` : ''}
${metadata.stats?.driftFindings ? `- [Drift Report](${baseUrl}/drift)` : ''}
`;
}

function generateRoutePage(route: RoutePageData, _baseUrl: string): string {
  const methodColors: Record<string, string> = {
    GET: 'green',
    POST: 'blue',
    PUT: 'yellow',
    PATCH: 'orange',
    DELETE: 'red',
  };
  void methodColors;

  return `# ${route.method} ${route.path}

## Overview

| Property | Value |
|----------|-------|
| Method | **${route.method}** |
| Path | \`${route.path}\` |
| Confidence | ${route.confidence} |

${
  route.handler
    ? `## Handler

**${route.handler.name}**

Source: \`${route.handler.file}:${route.handler.line}\`
`
    : ''
}

${
  route.schemas?.request
    ? `## Request Schema

- **Name:** \`${route.schemas.request.name}\`
- **Source:** \`${route.schemas.request.file}:${route.schemas.request.line}\`
`
    : ''
}

${
  route.openapi?.operationId
    ? `## OpenAPI

- Operation ID: \`${route.openapi.operationId}\`
`
    : ''
}
`;
}

function generatePackagePage(pkg: PackagePageData, _baseUrl: string): string {
  return `# ${pkg.name}

${pkg.version ? `**Version:** ${pkg.version}\n` : ''}
${pkg.description ? `\n${pkg.description}\n` : ''}

## Overview

| Property | Value |
|----------|-------|
| Source | \`${pkg.directory}\` |

${
  pkg.dependencies.length > 0
    ? `## Dependencies

${pkg.dependencies.map((d) => `- \`${d}\``).join('\n')}
`
    : ''
}
`;
}

function generateSchemaPage(schema: SchemaPageData, _baseUrl: string): string {
  return `# ${schema.name}

## Overview

| Property | Value |
|----------|-------|
| Source | \`${schema.file}:${schema.line}\` |
| Confidence | ${schema.confidence} |

${
  schema.properties.length > 0
    ? `## Properties

| Name | Type | Required | Description |
|------|------|----------|-------------|
${schema.properties.map((p) => `| \`${p.name}\` | \`${p.type}\` | ${p.required ? 'Yes' : 'No'} | ${p.description ?? '-'} |`).join('\n')}
`
    : ''
}
`;
}

function generateDriftReportPage(findings: DriftFindingData[]): string {
  const bySeverity = {
    error: findings.filter((f) => f.severity === 'error'),
    warning: findings.filter((f) => f.severity === 'warning'),
    info: findings.filter((f) => f.severity === 'info'),
  };

  return `# Drift Report

${findings.length > 0 ? `Found **${findings.length}** drift findings.` : 'No drift detected.'}

## Summary

| Severity | Count |
|----------|-------|
| Error | ${bySeverity.error.length} |
| Warning | ${bySeverity.warning.length} |
| Info | ${bySeverity.info.length} |

${
  bySeverity.error.length > 0
    ? `## Errors

${bySeverity.error.map((f) => generateDriftFindingMarkdown(f)).join('\n')}

`
    : ''
}
${
  bySeverity.warning.length > 0
    ? `## Warnings

${bySeverity.warning.map((f) => generateDriftFindingMarkdown(f)).join('\n')}

`
    : ''
}
${
  bySeverity.info.length > 0
    ? `## Info

${bySeverity.info.map((f) => generateDriftFindingMarkdown(f)).join('\n')}
`
    : ''
}
`;
}

function generateDriftFindingMarkdown(finding: DriftFindingData): string {
  const evidenceList = finding.evidence
    .map(
      (e) => `  - \`${e.file}\`${e.line ? `:${e.line}` : ''}${e.context ? ` — ${e.context}` : ''}`
    )
    .join('\n');

  return `### ${finding.entityName}

**Severity:** ${finding.severity}
**Type:** ${finding.entityType}

**Problem:** ${finding.problem}
${finding.expected ? `**Expected:** ${finding.expected}` : ''}
${finding.actual ? `**Actual:** ${finding.actual}` : ''}

**Evidence:**
${evidenceList || '  - No evidence available'}

**Suggested Action:** ${finding.suggestedAction}
`;
}
