/**
 * Fumadocs-compatible content generator for Peria.
 *
 * The wiki builder owns the source-backed markdown pages. This module converts
 * those pages into MDX and emits the small Fumadocs config files needed by a
 * Next/Fumadocs app.
 */

import type { WikiManifest, WikiPage } from '@peria/core';

export interface FumadocsContentOptions {
  manifest: WikiManifest;
  pages: WikiPage[];
  baseUrl?: string;
  contentDir?: string;
}

export interface FumadocsOutputFile {
  path: string;
  content: string;
}

export interface FumadocsOutput {
  files: FumadocsOutputFile[];
  pageTree: PageTreeNode[];
  pageCount: number;
}

export interface PageTreeNode {
  title: string;
  slug?: string;
  children?: PageTreeNode[];
}

function escapeYaml(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ');
}

function normalizeSlug(slug: string): string {
  return slug.replace(/^\/+|\/+$/g, '') || 'index';
}

function pathForPage(contentDir: string, page: WikiPage): string {
  return `${contentDir}/${normalizeSlug(page.slug)}.mdx`;
}

function convertMarkdownToMdx(markdown: string): string {
  return markdown.replace(/<([^>\n]+@[^>\n]+)>/g, '&lt;$1&gt;');
}

function renderSources(page: WikiPage): string {
  if (page.sourcePaths.length === 0) {
    return '';
  }

  return [
    '',
    '## Sources',
    '',
    ...page.sourcePaths.map((sourcePath) => `- \`${sourcePath}\``),
  ].join('\n');
}

function renderMdxPage(page: WikiPage): string {
  return [
    '---',
    `title: "${escapeYaml(page.title)}"`,
    `description: "${escapeYaml(page.description)}"`,
    '---',
    '',
    convertMarkdownToMdx(page.body),
    renderSources(page),
    '',
  ].join('\n');
}

function buildPageTree(manifest: WikiManifest): PageTreeNode[] {
  return manifest.tree.map((section) => ({
    title: section.title,
    children: section.pages.map((slug) => {
      const page = manifest.pages.find((item) => item.slug === slug);
      return {
        title: page?.title ?? slug,
        slug,
      };
    }),
  }));
}

function buildMetaJson(manifest: WikiManifest): string {
  const pageSlugs = new Set(manifest.pages.map((page) => page.slug));
  const pages: string[] = [];

  for (const section of manifest.tree) {
    pages.push(`---${section.title}---`);

    for (const slug of section.pages) {
      if (pageSlugs.has(slug)) {
        pages.push(slug);
      }
    }
  }

  for (const page of manifest.pages) {
    if (!pages.includes(page.slug)) {
      pages.push(page.slug);
    }
  }

  return `${JSON.stringify(
    {
      title: manifest.title,
      pages,
    },
    null,
    2
  )}\n`;
}

function buildSourceConfig(contentDir: string): string {
  return `import { defineConfig, defineDocs } from 'fumadocs-mdx/config';

export const docs = defineDocs({
  dir: '${contentDir}',
});

export default defineConfig();
`;
}

function buildSourceModule(baseUrl: string): string {
  return `import { docs } from 'collections/server';
import { loader } from 'fumadocs-core/source';

export const source = loader({
  baseUrl: '${baseUrl}',
  source: docs.toFumadocsSource(),
});
`;
}

function buildReadme(manifest: WikiManifest): string {
  return [
    `# ${manifest.title}`,
    '',
    'This directory contains Fumadocs-compatible output generated by Peria.',
    '',
    'Generated files:',
    '',
    '- `content/docs/**/*.mdx` wiki pages',
    '- `content/docs/meta.json` sidebar metadata',
    '- `source.config.ts` Fumadocs MDX collection config',
    '- `lib/source.ts` loader module for a Next/Fumadocs app',
    '- `wiki-manifest.json` Peria page manifest',
    '',
    'Install the Fumadocs app dependencies in the host project and import `source` from `lib/source.ts`.',
    '',
  ].join('\n');
}

export function generateFumadocsContent(options: FumadocsContentOptions): FumadocsOutput {
  const { manifest, pages, baseUrl = '/docs', contentDir = 'content/docs' } = options;
  const pageTree = buildPageTree(manifest);
  const files: FumadocsOutputFile[] = [
    ...pages.map((page) => ({
      path: pathForPage(contentDir, page),
      content: renderMdxPage(page),
    })),
    {
      path: `${contentDir}/meta.json`,
      content: buildMetaJson(manifest),
    },
    {
      path: 'source.config.ts',
      content: buildSourceConfig(contentDir),
    },
    {
      path: 'lib/source.ts',
      content: buildSourceModule(baseUrl),
    },
    {
      path: 'README.md',
      content: buildReadme(manifest),
    },
  ];

  return { files, pageTree, pageCount: pages.length };
}
