/**
 * Fumadocs-compatible content generator for Peria.
 *
 * The wiki builder owns the source-backed markdown pages. This module converts
 * those pages into MDX and emits the small Fumadocs config files needed by a
 * Next/Fumadocs app.
 */

import type { WikiManifest, WikiPage } from '@peria/core';

export interface FumadocsContentOptions {
  manifest: WikiManifest;
  pages: WikiPage[];
  baseUrl?: string;
  contentDir?: string;
}

export interface FumadocsOutputFile {
  path: string;
  content: string;
}

export interface FumadocsOutput {
  files: FumadocsOutputFile[];
  pageTree: PageTreeNode[];
  pageCount: number;
}

export interface PageTreeNode {
  title: string;
  slug?: string;
  children?: PageTreeNode[];
}

export interface SearchIndexEntry {
  title: string;
  slug: string;
  url: string;
  description: string;
  headings: string[];
  sources: string[];
}

function escapeYaml(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, ' ');
}

function normalizeSlug(slug: string): string {
  return slug.replace(/^\/+|\/+$/g, '') || 'index';
}

function pathForPage(contentDir: string, page: WikiPage): string {
  return `${contentDir}/${normalizeSlug(page.slug)}.mdx`;
}

function convertMarkdownToMdx(markdown: string, title: string): string {
  const escaped = markdown.replace(/<([^>\n]+@[^>\n]+)>/g, '&lt;$1&gt;');
  const titlePattern = /^#\s+(.+?)\s*$/m;
  const match = escaped.match(titlePattern);
  if (match && match[1].trim().toLowerCase() === title.trim().toLowerCase()) {
    return escaped.replace(titlePattern, '').replace(/^\n+/, '');
  }
  return escaped;
}

function renderSources(page: WikiPage): string {
  if (page.sourcePaths.length === 0) {
    return '';
  }

  return [
    '',
    '## Sources',
    '',
    ...page.sourcePaths.map((sourcePath) => `- \`${sourcePath}\``),
  ].join('\n');
}

function renderMdxPage(page: WikiPage): string {
  return [
    '---',
    `title: "${escapeYaml(page.title)}"`,
    `description: "${escapeYaml(page.description)}"`,
    '---',
    '',
    convertMarkdownToMdx(page.body, page.title),
    renderSources(page),
    '',
  ].join('\n');
}

function buildUrl(baseUrl: string, slug: string): string {
  const base = baseUrl.replace(/\/+$/g, '');
  return `${base}/${normalizeSlug(slug)}`;
}

function extractHeadings(markdown: string): string[] {
  return markdown
    .split('\n')
    .filter((line) => /^#{2,4}\s+/.test(line))
    .map((line) => line.replace(/^#+\s+/, '').trim())
    .filter(Boolean);
}

function buildSearchIndex(baseUrl: string, pages: WikiPage[]): string {
  const entries: SearchIndexEntry[] = pages.map((page) => ({
    title: page.title,
    slug: page.slug,
    url: buildUrl(baseUrl, page.slug),
    description: page.description,
    headings: extractHeadings(page.body),
    sources: page.sourcePaths,
  }));

  return `${JSON.stringify(entries, null, 2)}\n`;
}

function buildPageTree(manifest: WikiManifest): PageTreeNode[] {
  return manifest.tree.map((section) => ({
    title: section.title,
    children: section.pages.map((slug) => {
      const page = manifest.pages.find((item) => item.slug === slug);
      return {
        title: page?.title ?? slug,
        slug,
      };
    }),
  }));
}

function buildMetaJson(manifest: WikiManifest): string {
  const pageSlugs = new Set(manifest.pages.map((page) => page.slug));
  const pages: string[] = [];

  for (const section of manifest.tree) {
    pages.push(`---${section.title}---`);

    for (const slug of section.pages) {
      if (pageSlugs.has(slug)) {
        pages.push(slug);
      }
    }
  }

  for (const page of manifest.pages) {
    if (!pages.includes(page.slug)) {
      pages.push(page.slug);
    }
  }

  return `${JSON.stringify(
    {
      title: manifest.title,
      pages,
    },
    null,
    2
  )}\n`;
}

function buildReadme(manifest: WikiManifest): string {
  return [
    `# ${manifest.title}`,
    '',
    'This directory contains Fumadocs-compatible output generated by Peria.',
    '',
    'Generated files:',
    '',
    '- `content/docs/**/*.mdx` wiki pages',
    '- `content/docs/meta.json` sidebar metadata',
    '- `search-index.json` compact page/entity search index',
    '- `wiki-manifest.json` Peria page manifest',
    '- `pages/**/*.md` raw markdown mirror (also available via `@peria/adapters`)',
    '',
    'Preview locally:',
    '',
    '```sh',
    'peria serve',
    '```',
    '',
    'This serves the bundled TanStack Start + Fumadocs preview app from',
    '`@peria/renderer` against `content/docs`. To consume the content from a',
    'custom Fumadocs/Next app, point its `fumadocs-mdx` collection `dir` at',
    '`content/docs` and reuse these MDX files directly.',
    '',
  ].join('\n');
}

export function generateFumadocsContent(options: FumadocsContentOptions): FumadocsOutput {
  const { manifest, pages, baseUrl = '/docs', contentDir = 'content/docs' } = options;
  const pageTree = buildPageTree(manifest);
  const files: FumadocsOutputFile[] = [
    ...pages.map((page) => ({
      path: pathForPage(contentDir, page),
      content: renderMdxPage(page),
    })),
    {
      path: `${contentDir}/meta.json`,
      content: buildMetaJson(manifest),
    },
    {
      path: 'README.md',
      content: buildReadme(manifest),
    },
    {
      path: 'search-index.json',
      content: buildSearchIndex(baseUrl, pages),
    },
  ];

  return { files, pageTree, pageCount: pages.length };
}
