/**
 * Fumadocs-compatible content generator for Peria
 *
 * Generates MDX files with frontmatter and a content.config.ts
 * compatible with Fumadocs v13.
 */

import type { PeriaManifest } from '@peria/core';
import { generatePagesFromManifest } from './content.js';
import type { GeneratedPage } from './types.js';

export interface FumadocsContentOptions {
  /** Peria manifest to generate from */
  manifest: PeriaManifest;

  /** Base URL for links */
  baseUrl?: string;

  /** Output directory relative to docs root */
  outputDir?: string;
}

export interface FumadocsOutput {
  /** MDX files to write: { path, content } */
  files: Array<{ path: string; content: string }>;

  /** Content config for Fumadocs */
  contentConfig: string;

  /** Page tree for navigation */
  pageTree: PageTreeNode[];
}

export interface PageTreeNode {
  title: string;
  href?: string;
  children?: PageTreeNode[];
}

// ============ Helper Functions ============

function encodeRoutePath(path: string): string {
  return encodeURIComponent(path.replace(/\//g, '_').replace(/:/g, '_'));
}

function encodePackageName(name: string): string {
  return name.replace('@', '_at_').replace('/', '_slash_');
}

function escapeYaml(str: string): string {
  return str.replace(/"/g, '\\"').replace(/\n/g, ' ');
}

function escapeString(str: string): string {
  return str.replace(/'/g, "\\'");
}

function generateFrontmatter(page: GeneratedPage): string {
  const fields: string[] = [];

  fields.push(`title: "${escapeYaml(page.title)}"`);

  if (page.description) {
    fields.push(`description: "${escapeYaml(page.description)}"`);
  }

  if (page.category) {
    fields.push(`tag: "${page.category}"`);
  }

  if (page.order !== undefined) {
    fields.push(`order: ${page.order}`);
  }

  return `---
${fields.join('\n')}
---`;
}

function convertToMdx(page: GeneratedPage): string {
  const frontmatter = generateFrontmatter(page);
  return `${frontmatter}\n\n${page.content}`;
}

function buildPageTree(
  routes: ReturnType<typeof generatePagesFromManifest>['routes'],
  packages: ReturnType<typeof generatePagesFromManifest>['packages'],
  schemas: ReturnType<typeof generatePagesFromManifest>['schemas'],
  driftFindings: ReturnType<typeof generatePagesFromManifest>['driftFindings'],
): PageTreeNode[] {
  const tree: PageTreeNode[] = [];

  // Start Here section
  tree.push({
    title: 'Start Here',
    children: [{ title: 'Overview', href: '/overview' }],
  });

  // API Routes section
  if (routes.length > 0) {
    tree.push({
      title: 'API',
      children: routes.slice(0, 20).map((r) => ({
        title: `${r.method} ${r.path}`,
        href: `/routes/${encodeRoutePath(r.path)}`,
      })),
    });
  }

  // Schemas section
  if (schemas.length > 0) {
    tree.push({
      title: 'Schemas',
      children: schemas.map((s) => ({
        title: s.name,
        href: `/schemas/${s.name}`,
      })),
    });
  }

  // Packages section
  if (packages.length > 0) {
    tree.push({
      title: 'Packages',
      children: packages.map((p) => ({
        title: p.name,
        href: `/packages/${encodePackageName(p.name)}`,
      })),
    });
  }

  // Drift section
  if (driftFindings.length > 0) {
    tree.push({
      title: 'Maintenance',
      children: [{ title: 'Drift Report', href: '/drift' }],
    });
  }

  return tree;
}

function pageTreeToTreeValue(nodes: PageTreeNode[], indent = 2): string {
  const spaces = ' '.repeat(indent);
  const lines: string[] = [];

  for (const node of nodes) {
    if (node.children && node.children.length > 0) {
      lines.push(`${spaces}{`);
      lines.push(`${spaces}  title: '${escapeString(node.title)}',`);
      lines.push(`${spaces}  children: [`);
      lines.push(pageTreeToTreeValue(node.children, indent + 2));
      lines.push(`${spaces}  ],`);
      lines.push(`${spaces}},`);
    } else {
      lines.push(`${spaces}{`);
      lines.push(`${spaces}  title: '${escapeString(node.title)}',`);
      if (node.href) {
        lines.push(`${spaces}  href: '${node.href}',`);
      }
      lines.push(`${spaces}},`);
    }
  }

  return lines.join('\n');
}

function generateContentConfig(pageTree: PageTreeNode[]): string {
  const treeStr = pageTreeToTreeValue(pageTree);

  return `import { defineCollection } from 'fumadocs-core/mdx';
import { docsOptions, travelTree } from 'fumadocs-core/server';

const docs = defineCollection({
  ...docsOptions({
    rootDir: './content/docs',
  }),
});

// Fumadocs v13 content config
// ponytail: auto-generated by peria
export const { pages, tree } = travelTree({
  docs: {
${treeStr}
  },
});
`;
}

// ============ Main Export ============

/**
 * Generate Fumadocs-compatible content from Peria manifest
 */
export function generateFumadocsContent(options: FumadocsContentOptions): FumadocsOutput {
  const { manifest, baseUrl = '/docs' } = options;

  // Generate pages using existing content generator
  const { pages, routes, packages, schemas, driftFindings } =
    generatePagesFromManifest({ manifest, baseUrl });

  // Convert pages to MDX with frontmatter
  const files = pages.map((page) => ({
    path: page.slug.replace(/\//g, '_') + '.mdx',
    content: convertToMdx(page),
  }));

  // Generate page tree
  const pageTree = buildPageTree(routes, packages, schemas, driftFindings);

  // Generate content.config.ts
  const contentConfig = generateContentConfig(pageTree);

  return { files, contentConfig, pageTree };
}
