import { defineCollection } from 'fumadocs-core/mdx';
import { docsOptions, travelTree } from 'fumadocs-core/server';

const docs = defineCollection({
  ...docsOptions({
    rootDir: './content/docs',
  }),
});

// Fumadocs v13 content config
// ponytail: auto-generated by peria
export const { pages, tree } = travelTree({
  docs: {
  {
    title: 'Start Here',
    children: [
    {
      title: 'Overview',
      href: '/overview',
    },
    ],
  },
  },
});
