import { defineCollection } from 'fumadocs-core/mdx';
import { docsOptions, travelTree } from 'fumadocs-core/server';

const docs = defineCollection({
  ...docsOptions({
    rootDir: './content',
  }),
});

// Fumadocs v13 content config
// ponytail: auto-generated by peria
export const { pages, tree } = travelTree({
  docs,
  tree: [
  {
    page: {
      title: 'Start Here',
      children: [
      {
        title: 'Overview',
        url: '/overview',
      },
      ],
    },
  },
  ],
});
