/**
 * Express adapter for Peria
 *
 * Usage:
 * ```ts
 * import express from 'express'
 * import { periaDocs } from '@peria/adapters/express'
 *
 * const app = express()
 * app.use('/docs', periaDocs())
 * ```
 */

import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { isAbsolute, join, resolve } from 'node:path';
import express, { type Request, type Response, Router } from 'express';

export interface PeriaDocsOptions {
  /** Route path for docs (default: '/docs') */
  route?: string;
  /** Path to the docs directory generated by 'peria build' (default: 'docs') */
  docsPath?: string;
}

/**
 * Validate that a path is safe (no traversal)
 */
function validateDocsPath(docsPath: string): string {
  const base = isAbsolute(docsPath) ? docsPath : resolve(process.cwd(), docsPath);
  if (!existsSync(base)) {
    throw new Error(`Docs directory does not exist: ${docsPath}`);
  }
  return base;
}

/**
 * Create Express middleware for serving Peria documentation
 */
export function periaDocs(options: PeriaDocsOptions = {}): Router {
  const docsDir = validateDocsPath(options.docsPath ?? 'docs');
  const route = options.route ?? '/docs';

  const router = Router();

  // Serve static files (index.html, assets, wiki pages)
  router.use(express.static(docsDir));

  // API: serve wiki manifest
  router.get(`${route}/api/manifest.json`, async (_req: Request, res: Response) => {
    try {
      const manifestPath = join(docsDir, 'wiki-manifest.json');
      const content = await readFile(manifestPath, 'utf-8');
      res.json(JSON.parse(content));
    } catch {
      res.status(404).json({
        error: 'Manifest not found',
        message: 'Run "peria build" first to generate documentation',
      });
    }
  });

  // Serve llms.txt as plain text
  router.get(`${route}/llms.txt`, async (_req: Request, res: Response) => {
    try {
      const llmsPath = join(docsDir, 'ai-context.md');
      const content = await readFile(llmsPath, 'utf-8');
      res.type('text/plain').send(content);
    } catch {
      res
        .status(404)
        .type('text/plain')
        .send('# Documentation not available\n\nRun "peria build" first.');
    }
  });

  // Fallback to index.html for SPA-style navigation
  router.get(`${route}/*`, (_req: Request, res: Response) => {
    res.sendFile(join(docsDir, 'index.html'));
  });

  return router;
}
