/**
 * Express adapter for Peria
 *
 * Usage:
 * ```ts
 * import express from 'express'
 * import { periaDocs } from '@peria/adapters/express'
 *
 * const app = express()
 * app.use('/docs', periaDocs())
 * ```
 */

import express, { type Request, type Response, Router } from 'express';
import {
  missingDocsPayload,
  readLlmsText,
  readWikiManifest,
  resolveDocsPaths,
  resolveFallbackFile,
} from './shared.js';

export interface PeriaDocsOptions {
  /** Optional route path when mounting the returned router directly on the app */
  route?: string;
  /** Path to the docs directory generated by 'peria build' (default: 'docs') */
  docsPath?: string;
  /** Path to llms.txt generated by 'peria build' (default: sibling of docsPath) */
  llmsPath?: string;
}

/**
 * Create Express middleware for serving Peria documentation
 */
export function periaDocs(options: PeriaDocsOptions = {}): Router {
  const { docsDir, llmsPath } = resolveDocsPaths(options);

  const router = Router();

  // Serve generated docs files, including Fumadocs-compatible content.
  router.use(express.static(docsDir));

  // API: serve wiki manifest
  router.get('/api/manifest.json', async (_req: Request, res: Response) => {
    try {
      res.json(await readWikiManifest(docsDir));
    } catch {
      res.status(404).json({
        error: 'Manifest not found',
        message: 'Run "peria build" first to generate documentation',
      });
    }
  });

  // Serve llms.txt as plain text
  router.get('/llms.txt', async (_req: Request, res: Response) => {
    try {
      const content = await readLlmsText(llmsPath);
      res.type('text/plain').send(content);
    } catch {
      res
        .status(404)
        .type('text/plain')
        .send('# Documentation not available\n\nRun "peria build" first.');
    }
  });

  const sendFallback = (_req: Request, res: Response): void => {
    const fallback = resolveFallbackFile(docsDir);
    if (fallback) {
      res.sendFile(fallback);
      return;
    }

    res.status(404).json(missingDocsPayload(docsDir));
  };

  // Fallback to the generated reader entrypoint if present.
  router.get('/', sendFallback);
  router.get('/*', sendFallback);

  if (options.route) {
    const mountedRouter = Router();
    mountedRouter.use(options.route, router);
    return mountedRouter;
  }

  return router;
}
