/**
 * Fastify adapter for Peria
 *
 * Usage:
 * ```ts
 * import Fastify from 'fastify'
 * import { periaDocs } from '@peria/adapters/fastify'
 *
 * const app = Fastify()
 * await app.register(periaDocs, { routePrefix: '/docs' })
 * ```
 */

import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import fastifyStatic from '@fastify/static';
import type { FastifyInstance, FastifyRegisterOptions } from 'fastify';

export type { FastifyInstance } from 'fastify';

export interface PeriaDocsOptions {
  /** Route prefix for docs (default: '/docs') */
  routePrefix?: string;
  /** Path to the docs directory generated by 'peria build' (default: 'docs') */
  docsPath?: string;
}

/**
 * Create a Fastify plugin for serving Peria documentation
 */
export function periaDocs(
  options: PeriaDocsOptions = {}
): (app: FastifyInstance, opts: FastifyRegisterOptions<unknown>) => Promise<void> {
  const docsPath = options.docsPath ?? 'docs';
  const routePrefix = options.routePrefix ?? '/docs';

  return async (app: FastifyInstance, _opts: FastifyRegisterOptions<unknown>): Promise<void> => {
    // Register static file serving
    await app.register(fastifyStatic, {
      root: docsPath,
      prefix: `${routePrefix}/`,
      prefixAvoidTrailingSlash: true,
    });

    // API: serve wiki manifest
    app.get(`${routePrefix}/api/manifest.json`, async (_req, reply) => {
      try {
        const manifestPath = join(docsPath, 'wiki-manifest.json');
        const content = await readFile(manifestPath, 'utf-8');
        return reply.type('application/json').send(content);
      } catch {
        return reply
          .status(404)
          .type('application/json')
          .send(
            JSON.stringify({
              error: 'Manifest not found',
              message: 'Run "peria build" first to generate documentation',
            })
          );
      }
    });

    // Serve llms.txt as plain text
    app.get(`${routePrefix}/llms.txt`, async (_req, reply) => {
      try {
        const llmsPath = join(docsPath, 'ai-context.md');
        const content = await readFile(llmsPath, 'utf-8');
        return reply.type('text/plain').send(content);
      } catch {
        return reply
          .status(404)
          .type('text/plain')
          .send('# Documentation not available\n\nRun "peria build" first.');
      }
    });

    // Fallback to index.html for SPA-style navigation
    app.get(`${routePrefix}/*`, async (_req, reply) => {
      return reply.sendFile('index.html');
    });
  };
}
