/**
 * Fastify adapter for Peria
 *
 * Usage:
 * ```ts
 * import Fastify from 'fastify'
 * import { periaDocs } from '@peria/adapters/fastify'
 *
 * const app = Fastify()
 * await app.register(periaDocs, { routePrefix: '/docs' })
 * ```
 */

import fastifyStatic from '@fastify/static';
import type { FastifyInstance, FastifyRegisterOptions, FastifyReply } from 'fastify';
import {
  missingDocsPayload,
  readLlmsText,
  readWikiManifest,
  resolveDocsPaths,
  resolveFallbackFile,
} from './shared.js';

export type { FastifyInstance } from 'fastify';

export interface PeriaDocsOptions {
  /** Route prefix for docs (default: '/docs') */
  routePrefix?: string;
  /** Path to the docs directory generated by 'peria build' (default: 'docs') */
  docsPath?: string;
  /** Path to llms.txt generated by 'peria build' (default: sibling of docsPath) */
  llmsPath?: string;
}

/**
 * Create a Fastify plugin for serving Peria documentation
 */
export function periaDocs(
  options: PeriaDocsOptions = {}
): (app: FastifyInstance, opts: FastifyRegisterOptions<unknown>) => Promise<void> {
  const { docsDir, llmsPath } = resolveDocsPaths(options);
  const routePrefix = options.routePrefix ?? '/docs';

  return async (app: FastifyInstance, _opts: FastifyRegisterOptions<unknown>): Promise<void> => {
    // Register generated docs file serving.
    await app.register(fastifyStatic, {
      root: docsDir,
      prefix: `${routePrefix}/`,
      prefixAvoidTrailingSlash: true,
      wildcard: false,
    });

    // API: serve wiki manifest
    app.get(`${routePrefix}/api/manifest.json`, async (_req, reply) => {
      try {
        return reply.type('application/json').send(await readWikiManifest(docsDir));
      } catch {
        return reply
          .status(404)
          .type('application/json')
          .send(
            JSON.stringify({
              error: 'Manifest not found',
              message: 'Run "peria build" first to generate documentation',
            })
          );
      }
    });

    // Serve llms.txt as plain text
    app.get(`${routePrefix}/llms.txt`, async (_req, reply) => {
      try {
        const content = await readLlmsText(llmsPath);
        return reply.type('text/plain').send(content);
      } catch {
        return reply
          .status(404)
          .type('text/plain')
          .send('# Documentation not available\n\nRun "peria build" first.');
      }
    });

    const sendFallback = async (reply: FastifyReply): Promise<unknown> => {
      const fallback = resolveFallbackFile(docsDir);
      if (!fallback) {
        return reply.status(404).type('application/json').send(missingDocsPayload(docsDir));
      }

      const content = await readLlmsText(fallback);
      return reply.type(fallback.endsWith('.html') ? 'text/html' : 'text/markdown').send(content);
    };

    // Fallback to index.html for old static output or README.md for Fumadocs output.
    app.get(routePrefix, async (_req, reply) => sendFallback(reply));
    app.get(`${routePrefix}/*`, async (_req, reply) => sendFallback(reply));
  };
}
