/**
 * NestJS adapter for Peria
 *
 * Usage:
 * ```ts
 * import { setupPeriaDocs } from '@peria/adapters/nest'
 *
 * // In your main.ts or app.module.ts
 * setupPeriaDocs(app, {
 *   route: '/docs'
 * })
 * ```
 */

import { join } from 'node:path';
import type { NestApplication } from '@nestjs/core';
import express from 'express';

export type { NestApplication } from '@nestjs/core';

export interface PeriaNestOptions {
  /** Route path for docs (default: '/docs') */
  route?: string;
  /** Path to the docs directory generated by 'peria build' (default: 'docs') */
  docsPath?: string;
}

/**
 * Set up Peria documentation middleware in a NestJS application
 */
export function setupPeriaDocs(app: NestApplication, options: PeriaNestOptions = {}): void {
  const docsPath = options.docsPath ?? 'docs';
  const route = options.route ?? '/docs';

  // Use Express static serving under the docs route
  app.use(route, express.static(docsPath));

  // Fallback to index.html for SPA navigation
  app.use(`${route}/*`, express.static(join(docsPath, 'index.html')));
}
