/**
 * NestJS adapter for Peria
 *
 * Usage:
 * ```ts
 * import { setupPeriaDocs } from '@peria/adapters/nest'
 *
 * // In your main.ts or app.module.ts
 * setupPeriaDocs(app, {
 *   route: '/docs'
 * })
 * ```
 */

import type { NestApplication } from '@nestjs/core';
import express, { type Request, type Response } from 'express';
import {
  missingDocsPayload,
  readLlmsText,
  readWikiManifest,
  resolveDocsPaths,
  resolveFallbackFile,
} from './shared.js';

export type { NestApplication } from '@nestjs/core';

export interface PeriaNestOptions {
  /** Route path for docs (default: '/docs') */
  route?: string;
  /** Path to the docs directory generated by 'peria build' (default: 'docs') */
  docsPath?: string;
  /** Path to llms.txt generated by 'peria build' (default: sibling of docsPath) */
  llmsPath?: string;
}

/**
 * Set up Peria documentation middleware in a NestJS application
 */
export function setupPeriaDocs(app: NestApplication, options: PeriaNestOptions = {}): void {
  const { docsDir, llmsPath } = resolveDocsPaths(options);
  const route = options.route ?? '/docs';

  // Get the underlying Express/Fastify instance
  // NestJS uses Express by default (or Fastify with @nestjs/platform-fastify)
  const httpAdapter = app.getHttpAdapter();
  const instance = httpAdapter.getInstance();

  // Check if we have an Express-compatible instance
  if (!instance || typeof instance.use !== 'function') {
    console.warn(
      '[peria] NestJS adapter: unsupported HTTP adapter. ' +
        'Only Express and Fastify are supported natively.'
    );
    return;
  }

  // Serve generated docs files, including Fumadocs-compatible content.
  instance.use(route, express.static(docsDir));

  // API: serve wiki manifest
  instance.get(`${route}/api/manifest.json`, async (_req: Request, res: Response) => {
    try {
      res.json(await readWikiManifest(docsDir));
    } catch {
      res.status(404).json({
        error: 'Manifest not found',
        message: 'Run "peria build" first to generate documentation',
      });
    }
  });

  // Serve llms.txt as plain text
  instance.get(`${route}/llms.txt`, async (_req: Request, res: Response) => {
    try {
      const content = await readLlmsText(llmsPath);
      res.type('text/plain').send(content);
    } catch {
      res
        .status(404)
        .type('text/plain')
        .send('# Documentation not available\n\nRun "peria build" first.');
    }
  });

  const sendFallback = (_req: Request, res: Response): void => {
    const fallback = resolveFallbackFile(docsDir);
    if (fallback) {
      res.sendFile(fallback);
      return;
    }

    res.status(404).json(missingDocsPayload(docsDir));
  };

  // Fallback to the generated reader entrypoint if present.
  instance.get(route, sendFallback);
  instance.get(`${route}/*`, sendFallback);
}
